<?php

namespace SenseiTarzan\HomesManager;

use pocketmine\plugin\PluginBase;
use pocketmine\utils\SingletonTrait;
use SenseiTarzan\ExtraEvent\Component\EventLoader;
use SenseiTarzan\HomesManager\Commands\HomeCommand;
use SenseiTarzan\HomesManager\Component\HomeManager;
use SenseiTarzan\HomesManager\Component\HomePlayerManager;
use SenseiTarzan\HomesManager\Listener\PlayerListener;
use SenseiTarzan\LanguageSystem\Component\LanguageManager;

class Main extends PluginBase
{

    use SingletonTrait;

    protected function onLoad(): void
    {
        self::setInstance($this);
        define("SenseiTarzan\\HomesManager\\PLUGIN_DATA_PATH", $this->getDataFolder());
        new HomeManager($this);
        new HomePlayerManager();
        new LanguageManager($this);
        parent::onLoad(); // TODO: Change the autogenerated stub
    }

    protected function onEnable(): void
    {
        EventLoader::loadEventWithClass($this, PlayerListener::class);
        $this->getServer()->getCommandMap()->register("senseitarzan", new HomeCommand($this,"home"));
        LanguageManager::getInstance()->loadCommands("home");
        parent::onEnable(); // TODO: Change the autogenerated stub
    }

}